DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	phone VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	password VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	created_by VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	created_date DATA NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);